### ISSUE TITLE
Manually

### ISSUE THREAD

**Issue by snack373** [fbsanches/cordova-plugin-wallpaper#1]
Can i install this plagin manually (i am using phonegap build)?

**Comment by fbsanches** [comment]
@snack373 Yes. I believe so because I did manually installations it in my tests and worked properly. Try to catch the zip and install manual. Good luck and hugs.

**Comment by janbaudisch** [comment]
Why not just specify this plugin in your config.xml?

**Comment by fbsanches** [comment]
ok
