### ISSUE TITLE
success function

### ISSUE THREAD

**Issue by db3344** [fbsanches/cordova-plugin-wallpaper#11]
How Can I call success function?
`success = function() { alert("Success"); }; `

**Comment by janbaudisch** [comment]
I don't understand your question. What success function?

**Comment by db3344** [comment]
I need this funqcion it is in other plugin...

```
  var success = function() { alert("Success"); };           // Do something on success return.
  var error = function(message) { alert("Oopsie! " + message); };   // Do something on error return.
```
how can I receive Success alert?

**Comment by db3344** [comment]
I Find Solution Super plugin Thanks
