### ISSUE TITLE
Issue with getting image src automatically

### ISSUE THREAD

**Issue by sajjadalis** [fbsanches/cordova-plugin-wallpaper#12]
When i use hardcoded image src similar to examples here. It works fine.
```
function wp() {
    window.plugins.wallpaper.setImage("images/1462204239933.jpg");
}
```
But if i try to get image src automatically from active slide. It won't set wallpaper.
```
function wp() {
    var picture = $$(".swiper-slide-active").find(".pic").attr('src');
    window.plugins.wallpaper.setImage('"'+picture+'"');
}
```
I checked console.log and it's getting image src fine for each slide. What am i doing wrong? Would appreciate help.

Thanks for this plugin.

**Comment by janbaudisch** [comment]
This is because `setImage` can only use local paths.
I guess, your slider image sources are http urls? The you have to use `setImageHttp`.
If they are Base64-encoded sources, you will have to use `setImageBase64.`
For further information look at the README.

PS: `picture` in your example is already a string.

**Comment by sajjadalis** [comment]
Thanks for reply.

They're not http urls. All images resides in images/ folder. But what i'm trying to do is to get all links on a single fixed button. I'm using Framework7 and Floating Action button in bottom right corner looks perfect.

So there is no way to get images link with jquery based on active class?

**Comment by janbaudisch** [comment]
Ah, I see, my fault.
You said now errors or logs?
Could you post one of the sources as an example?

**Comment by sajjadalis** [comment]
Setup is really simple.

HTML
```
<div class="page-content">
           <button class="setwp floating-button"><i class="icon icon-plus"></i></button>
          <div class="swiper-container">
                <div class="swiper-wrapper">
                    <div class="swiper-slide"><img src="images/001.jpg" rel="1"></div>
                    <div class="swiper-slide"><img src="images/002.jpg" rel="2"></div>
                    <div class="swiper-slide"><img src="images/003.jpg" rel="3"></div>
                </div>
          </div>
</div>
```
JS
```
// .swiper-slide-active class for active slide
function wp() {
    var wppic = $$(".swiper-slide-active").find("img").attr('src');
    window.plugins.wallpaper.setImage('"'+wppic+'"');
}
function wpalert() {
	alert('Wallpaper is set');
}
$$('.setwp').on('click', function (e) {
     wp(); wpalert();
});
```

When i set console log in wp() function. It displays getting src link for each image.

```
function wp() {
    var wppic = $$(".swiper-slide-active").find(".pic").attr('src');
   console.log('"'+wppic+'"');
}
```
Here is the screenshot of console log. http://prntscr.com/f7ahcj/direct

I just tried to hardcode all images in wp() function and get them with rel attribute.

```
function wp() {
    var rel = $$(".swiper-slide-active").find("img").attr('rel');
    if (rel == 1) { 
        window.plugins.wallpaper.setImage("images/001.jpg");
    } else if (rel == 2) { 
        window.plugins.wallpaper.setImage("images/002.jpg");
    } else if (rel == 3) { 
        window.plugins.wallpaper.setImage("images/003.jpg");
    }
}
```
But that is also not working. Again no error in console log. So far only this method is working.

```
function wp() {
        window.plugins.wallpaper.setImage("images/001.jpg");
}
function wpalert() {
	alert('Wallpaper is set');
}
$$('.setwp').on('click', function (e) {
     wp(); wpalert();
});
```
One more thing. If i add onclick directly in button. That won't work either.

```
<button onclick="window.plugins.wallpaper.setImage("images/001.jpg");" class="floating-button"><i class="icon icon-plus"></i></button>
```
Not sure what am i doing wrong.

Would really love if that first method somehow work. It would keep js file very simple while i can easily add lots of images in the app.

Thanks

**Comment by sajjadalis** [comment]
Just tried this not so elegant method but its working for a single button. :)

```
function wp1() {
    window.plugins.wallpaper.setImage("images/001.jpg");
}
function wp2() {
    window.plugins.wallpaper.setImage("images/002.jpg");
}
function wp3() {
    window.plugins.wallpaper.setImage("images/003.jpg");
}

$$('.setwp').on('click', function (e) {
    var rel = $$(".swiper-slide-active").find("img").attr('rel');
    if (rel == 1) { 
        wp1(); 
    } else if (rel == 2) { 
        wp2();
    } else if (rel == 3) { 
        wp3();
    };
    toast.show();
});
```
But again, my earlier code might be ugly as well. If someone can help me to do this in a better way. Would appreciate that.

**Comment by janbaudisch** [comment]
Is there any reason to use `'"'+wppic+'"'`? If you use `.attr()` it should already be a string. You can't make a string more string-like.
So maybe you just use your `wppic` as the source, without some stringifying.

**Comment by sajjadalis** [comment]
Well. I'm an idiot. The reason i was trying to stringifying was to follow example under installation method. `window.plugins.wallpaper.setImage("img/mybackground.jpg");` .. I didn't know .attr() would be already a string (noob). So i thought unless i add strings separately it wouldn't work.. It didn't cross my mind to just remove strings and test it.

Thanks for the help. Problem is solved. just `wppic` is working fine.

**Comment by janbaudisch** [comment]
Yes, that makes sense. Glad it worked!

Have a nice day!
