### ISSUE TITLE
Success and Error function?

### ISSUE THREAD

**Issue by sajjadalis** [fbsanches/cordova-plugin-wallpaper#14]
Hi,

How can i get success and error function when wallpaper is set or if there is any issue. I would like to show toast message like Wallpaper Successfully Set or if there is a problem. 

I found this issue. https://github.com/fbsanches/cordova-plugin-wallpaper/issues/11

But not sure how @db3344 did that. I would appreciate help. Thanks

**Comment by janbaudisch** [comment]
I added this functionality in #16. Until it is merged you can use my fork, where there is already a description on how to use the callback in the README.
Please note that I have not tested the functionality yet.

**Comment by sajjadalis** [comment]
Thanks @flyingP0tat0 for adding this functionality. Really appreciated.
