### ISSUE TITLE
external source

### ISSUE THREAD

**Issue by destata** [fbsanches/cordova-plugin-wallpaper#2]
hi.. can this plugin get from the external source ?

for ex: http://mydomain.com/image.jpg

**Comment by fbsanches** [comment]
I'm sorry. Not yet. Only within the same project. When you have time, or someone wants to collaborate can implement this functionality. Thanks for your interest.

**Comment by janbaudisch** [comment]
I created a pull request just now which will give you Base64 functionality. So if you are able to get you image in Base64 format this should be no problem anymore. (If my pull request is accepted...)
I already did something like that in an own project, so if you need further help let me know.
