### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by alij2016** [fbsanches/cordova-plugin-wallpaper#4]
Hi, this is not working for me.

Here are my codes:

`<img alt="Wallpaper" src="wallpapers/solid/1.png" onclick="window.plugins.wallpaper.setImage('wallpapers/solid/1.png');">`

I have the plugin in config.xml as "`<plugin name="cordova-plugin-wallpaper"/>`"

I have the Wallpaper.j file which you have as well. I am using PhoneGap Build.

Can you advise me?

**Comment by janbaudisch** [comment]
Could you please provide some Information about your Problem?

**Comment by fbsanches** [comment]
For now the image has to be within the www folder to work.

**Comment by alij2016** [comment]
Well, when i tap on the image, it does not set it as wallpaper. 

You mean like this?

`onclick="window.plugins.wallpaper.setImage('www/wallpapers/solid/1.png');">`

**Comment by fbsanches** [comment]
Our friend @flyingPotat0e  also made with encryption option with base64.

**Comment by alij2016** [comment]
Not working when tapped

`onclick="window.plugins.wallpaper.setImage('www/wallpapers/solid/1.png');">`

Bear in mind I did not create any folder named WWW.

**Comment by janbaudisch** [comment]
Oh, I'm sorry, my GitHub app didn't show your description of the problem to me...

**Comment by janbaudisch** [comment]
He just meant that your wallpapers folder needs to be in the www directory. But I guess it is? Try your first approach with the secod parameter set to false.

**Comment by alij2016** [comment]
not working again. here full code:
`
<img alt="Wallpaper" src="www/solid/1.png" onclick="window.plugins.wallpaper.setImage('www/solid/1.png',base64, false);`

**Comment by janbaudisch** [comment]
No, there are only two parameters... In your case it should be 1st path and 2 false. But only path should also work, so something else has to be wrong. I can't test this out in next few days, so I'm sorry, but it looks like I can't help you at this point.

**Comment by alij2016** [comment]
its working now thnaks

**Comment by janbaudisch** [comment]
Great to hear that

**Comment by janbaudisch** [comment]
I guess this one can be closed now...
