### ISSUE TITLE
Travis CI Badge

### ISSUE THREAD

**Issue by janbaudisch** [fbsanches/cordova-plugin-wallpaper#6]
@fbsanches Could you please manage to put your own Travis CI badge in README.md as the Android Build status? My own one will not update anymore as this isn't my project (or fork) anymore. If not maybe you should at least remove it so nobody gets confused.

**Comment by janbaudisch** [comment]
Well I just saw that you removed the CodeClimate badges...
Just a kindly reminder (that I meant the Travis badge, CodeClimate was allright)

**Comment by fbsanches** [comment]
how can I do this? help me

**Comment by janbaudisch** [comment]
You sign up at https://travis-ci.org (with you GitHub account, should be easy).
Then you add your project (this repository), let it build and change the link in README.md to your build (you will get Markdown code at TravisCI).

**Comment by fbsanches** [comment]
OK. Done! Thanks

**Comment by janbaudisch** [comment]
And while we are at it, could you please re-open #7 ?
There is a way to solve the problem.

**Comment by janbaudisch** [comment]
Alright, thank you, this can be closed now.

**Comment by fbsanches** [comment]
OK. Thank you.
