### ISSUE TITLE
Set wallpaper external

### ISSUE THREAD

**Issue by alij2016** [fbsanches/cordova-plugin-wallpaper#7]
Hi, I want to know if this plugin can set wallpapers which are stored on cloud. I tried this but did not work:
`
<button onclick="window.plugins.wallpaper.setImage('https://example.com/4izvk4qjx/image.jpg',false);></button>`

Just an example above, but you get the point. 

Thanks

**Comment by flyingP0tat0** [comment]
Hi,

**Comment by janbaudisch** [comment]
This is exactly what the setImageBase64 function is for. Just get your image as a Base64 string and pass it into the function.

**Comment by alij2016** [comment]
Not working:

`<button onclick="window.plugins.wallpaper.setImageBase64('data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4ge4SUN......',false)</button>`

**Comment by fbsanches** [comment]
For now only with local images. It does not work with clouds in images. Sorry, but I'm out of time and if anyone wants to help me I will be available. Thanks

**Comment by fbsanches** [comment]
Download the image and then set it.

**Comment by fbsanches** [comment]
How we could solve this?

**Comment by janbaudisch** [comment]
I will just look through my example code, wait a sec.

**Comment by janbaudisch** [comment]
So, the key is to retrieve your image in Base64 format. This is how I achieved that with an XMLHttpRequest:

``` javascript
var xhr = new XMLHttpRequest(); // create new request
xhr.responseType = "arraybuffer"; // tell our reuqest that we want an arraybuffer
xhr.onload = function() // gets executed when there is data (response)
{
    var array = new Uint8Array(xhr.response);
    var raw = ""; // variable for storing raw image data
    var chunk = 5000;
    for (i = 0; i < array.length; i += chunk)
    {
        var subArray = array.subarray(i, i + chunk);
        raw += String.fromCharCode.apply(null, subArray);
    }
    var base64 = btoa(raw); // convert byte toBase64
    window.plugins.wallpaper.setImageBase64(base64); // set image as wallpaper
};
xhr.open("GET", url, true); // your URL here
xhr.send(); // send request
```

This may be a bit confusing and I think we have to put this in the plugin as a own function. I will see what I can do but for now this should be a working solution.
I hope this will help you @alij2016

**Comment by fbsanches** [comment]
Cool, I'll wait then. If you need some help if not, let me know and I'll talk to my friends and ask for help. I think this implementation will be of great value for this plugin. Hugs

**Comment by janbaudisch** [comment]
I think I should get this done.
Just let this one open for @alij2016 to comment.

**Comment by janbaudisch** [comment]
@alij2016 Now you can easily use the implementation I made with one simple function:

``` javascript
window.plugins.wallpaper.setImageHttp("http://example.com/image.jpg");  // your url here
```

This should do the trick.

**Comment by fbsanches** [comment]
Good Job. Thanks

**Comment by alij2016** [comment]
Wow thank you fir adding this feature. I have not tested it yet.

I want to know if this will work on image links without extension like these links which are generated from Google Drive or One Drive.

Thanks

**Comment by janbaudisch** [comment]
It should

**Comment by janbaudisch** [comment]
The important thing is, that your url (link) has to begin with http or https an has to end with a image ending like .png or .jpg.

**Comment by janbaudisch** [comment]
Something like http://yourcloudhere.com/yourstorage/image.jpg

**Comment by alij2016** [comment]
But on many file hosting sites like Drive abd OneDrive it does not end with .jpg or any extention. Will it still works?

**Comment by janbaudisch** [comment]
What ending do the files have?

**Comment by alij2016** [comment]
Example here: https://drive.google.com/open?id=0B3KKpVby1FtSLVN3cmhIRFFvTkk

**Comment by janbaudisch** [comment]
I completely forgot about that. I will take a look at the problem. Will notify you if I got something.

**Comment by sajjadalis** [comment]
Hi @flyingP0tat0 

ImageHttp method is not working for me. Can you please help. I tried this earlier about a month ago and it didn't work. But at that time, remote images were not my goal, Now i tried it again and same issue.

I'm getting image URL fine in console.log and its a direct .jpg link starting with http. Works fine with x-socialsharing plugin. Any idea, what could be the issue. Would appreciate help. Thanks.

**Comment by flyingP0tat0** [comment]
If you show us the code you are using, we will be able to help you. So please provide us some code.

**Comment by janbaudisch** [comment]
@Key7i If you show us the code you are using, we will be able to help you. So please provide us some code.
Also you may want to open a new issue for that.

**Comment by sajjadalis** [comment]
@flyingP0tat0 Thanks for reply. I just posted a new issue.
https://github.com/fbsanches/cordova-plugin-wallpaper/issues/15

**Comment by fbsanches** [comment]
Posted new issue. https://github.com/fbsanches/cordova-plugin-wallpaper/issues/15. Close this issue. Thanks.

**Comment by AchrafABOUL** [comment]
Hey, the solution for this problem is by using the base64 of the image without the prefix 'data:image/jpeg;base64,' 
Which means in your example you can use :
<button onclick="window.plugins.wallpaper.setImageBase64('/9j/4AAQSkZJRgABAQEASABIAAD/4ge4SUN......',false)</button>

instead of:

<button onclick="window.plugins.wallpaper.setImageBase64('data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD/4ge4SUN......',false)</button>
